version: '3.8'


services:


  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: managementsystem
      POSTGRES_PASSWORD: secret
      TZ: UTC
    volumes:
      - managementsystem-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  managementsystem-pg-local: